//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contact.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<int> position_id { get; set; }
        public Nullable<int> organisation_id { get; set; }
        public Nullable<int> address_id { get; set; }
        public string mob_no { get; set; }
        public string alt_mob_no { get; set; }
        public string email { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual address address { get; set; }
        public virtual organisation organisation { get; set; }
        public virtual position position { get; set; }
    }
}
